env:
  global:
    - DJANGO_SETTINGS_MODULE=test_project.settings
  matrix:
    - DJANGO=1.2
    - DJANGO=1.3
    - DJANGO=1.4
    - DJANGO=1.5
    - DJANGO=1.6
    - DJANGO=1.7
install:
  - pip install django==${DJANGO}
  - pip install .
language: python
python:
  - "2.7"
script: python test_project/manage.py test alert_tests
